name: Python Unit Tests

on:
  push:
    branches:
      - '*'
    paths-ignore: ['*.md', 'LICENSE', 'checkpoints/*.pt']
  pull_request:
    branches:
      - '*'
    paths-ignore: ['*.md', 'LICENSE', 'checkpoints/*.pt']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download en_core_web_sm
        python utils/download.py

    - name: Test calc.py functionalities
      run: |
        python utils/calc.py --dataset_name artem9k/ai-text-detection-pile --model_name Qwen/Qwen2.5-0.5B-Instruct

    - name: Unzip data
      run: |
        cd data
        tar -xzvf Training_Essay_Data.tar.gz

    - name: Preprocess data
      run: |
        python utils/preprocess.py
    #     python utils/downscale.py

    # - name: Generate dataset
    #   run: |
    #     python utils/gen_dataset.py

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests
