name: Python Unit Tests

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download en_core_web_sm

    - name: Unzip data
      run: |
        cd data
        tar -xzvf Training_Essay_Data.tar.gz

    - name: Preprocess data
      run: |
        python utils/preprocess.py

    - name: Generate dataset
      run: |
        python utils/gen_dataset.py

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-
